greenCRM/client/urls.py
from django.urls import path

from . import views

app_name = 'clients'

urlpatterns = [
    path('', views.clients_list, name='list'),
    path('<int:pk>/', views.clients_detail, name='detail'),
    path('<int:pk>/delete/', views.clients_delete, name='delete'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('<int:pk>/add-comment/', views.clients_detail, name='add_comment'),
    path('<int:pk>/add-file/', views.clients_add_file, name='add_file'),
    path('add/', views.clients_add, name='add'),
    path('export/', views.clients_export, name='export'),
    path('report/', views.clients_report, name='report'),
    
]

greenCRM/dashboard/urls.py
from django.urls import path

from . import views 

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='index'), # can be left empty because dashbord url is located in greenCRM url file
]

greenCRM/greenCRM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about
from userprofile.forms import LoginForm


urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include ('lead.urls')), # configuring all urls beginning with dashboard/leads
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/', include('dashboard.urls')), # setting all urls that begin with dashbord to use dashboard.urls file
    path('dashboard/teams/', include('team.urls')),
    path('dashboard/report/', include ('report.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

greenCRM/lead/urls.py
from django.urls import path

from . import views 

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name ='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name= 'detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='converted'),
    path('<int:pk>/add-comment', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name='add_file'),
    path('add/', views.LeadCreateView.as_view(), name='add'),
    path('export/', views.leads_export, name='export'),
]

greenCRM/client/models.py
from django.contrib.auth.models import User
from django.db import models

from team.models import Team


class Client(models.Model):
    team = models.ForeignKey(Team, related_name='clients', on_delete=models.CASCADE)
    name = models.CharField(max_length=225)
    org_name = models.CharField(max_length=225, default='unknown')
    email = models.EmailField()
    address = models.CharField(max_length=255, default='unknown')
    description = models.TextField(blank=True, null=True)
    monthly_order = models.IntegerField(default=0)
    total_order_value = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    customer_type = models.CharField(max_length=20, choices=(('restaurant', 'Restaurant'), ('store', 'Store')), default='unknown')
    created_by = models.ForeignKey(User, related_name='clients', on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    sales_rep = models.ForeignKey(User, related_name='clients_rep', on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        # Calculate the total_order_value based on monthly_order
        self.total_order_value = self.monthly_order * 29.95
        super(Client, self).save(*args, **kwargs)

class Comment(models.Model):
    team = models.ForeignKey(Team, related_name='client_comments', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='client_comments', on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

class ClientFile(models.Model):
    team = models.ForeignKey(Team, related_name='client_files', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='clientfiles') #location of folder for uplaod
    created_by = models.ForeignKey(User, related_name='client_files', on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

greenCRM/client/forms.py
from django import forms 


from . models import Client, Comment, ClientFile

class AddClientForm(forms.ModelForm):  #using modelForm so django will create this for us based on information in the clas meta
    class Meta:
        model = Client
        fields = ('name','org_name','email','address','description', 'customer_type', 'monthly_order', 'sales_rep')  #which fields I want to show in the form

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

class AddFileForm(forms.ModelForm):
    class Meta:
        model = ClientFile
        fields = ('file',)

greenCRM/client/views.py
import csv
import matplotlib.pyplot as plt

from django.contrib import messages 

from django.db.models import Sum

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from .forms import AddClientForm, AddCommentForm, AddFileForm
from .models import Client

from team.models import Team

@login_required
def clients_export(request):
    clients = Client.objects.filter(created_by=request.user)  #user created clients

    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attatchment; filename="clients.csv"'}
    )

    writer = csv.writer(response)
    writer.writerow(['Org Name','Contact', 'Address', 'Created at', 'Created by', 'Customer Type', 'Monthly Order', 'Total Order Value', 'Sales Rep'])
    
    for client in clients:   #looping through all the clients and adding them to the file:
        writer.writerow([client.org_name ,client.name, client.address, client.created_at, client.created_by, client.customer_type, client.monthly_order, client.total_order_value, client.sales_rep])

    return response

@login_required
def clients_list(request):
    clients = Client.objects.filter(created_by=request.user) #user create clients
    total_order_value = clients.aggregate(Sum('total_order_value'))['total_order_value__sum'] or 0
    total_monthly_order = sum(client.monthly_order for client in clients)

    return render(request, 'client/clients_list.html',{
        'clients': clients,
        'total_monthly_order':total_monthly_order,
        'total_order_value': total_order_value
    })

@login_required
def clients_add_file(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == 'POST':
        form = AddFileForm(request.POST, request.FILES)

        if form.is_valid():
            file = form.save(commit=False)
            file.team = request.user.userprofile.active_team
            file.created_by = request.user
            file.client_id = pk 
            file.save()

            return redirect('clients:detail', pk=pk)
    return redirect('clients:detail', pk=pk)

@login_required
def clients_detail(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == 'POST':
        form = AddCommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.team = request.user.userprofile.active_team
            comment.created_by = request.user
            comment.client = client
            comment.save()

            return redirect('clients:detail', pk=pk)
    else:
        form = AddCommentForm()

    return render(request, 'client/clients_detail.html', {
        'client': client,
        'form':form,
        'fileform': AddFileForm(),
    })

@login_required
def clients_add(request):
    team = request.user.userprofile.active_team

    if request.method == 'POST':
        form = AddClientForm(request.POST)

        if form.is_valid():
            client = form.save(commit=False)  #set commit=False to prevent saving in the database
            client.created_by = request.user
            client.team = team
            client.save()

            messages.success(request, 'New client created')

            return redirect('clients:list')
    else:  #If not a post request, return an empty form
        form = AddClientForm()

    return render(request, 'client/clients_add.html', {
        'form' : form,
        'team': team,
    })

@login_required
def clients_delete(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)
    client.delete()

    messages.success(request, 'Client has been deleted.')

    return redirect('clients:list')   # redirect user back to the clients_list page

@login_required
def clients_edit(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == 'POST':  # check if user has submitted
        form = AddClientForm(request.POST, instance=client)  # if user has submitted, create new form  instance=client is passing information for update

        if form.is_valid():
            form.save()

            messages.success(request, 'Changes to client saved') 

            return redirect('clients:list') 
    else:
        form = AddClientForm(instance=client)
    
    return render(request, 'client/clients_edit.html', {
        'form' : form 
    })

@login_required
def clients_report(request):
    data = Client.objects.all()
    context = {
        'data':data,
    }

    return render(request, 'client/clients_report.html', context)

greenCRM/client/templates/client/clients_add.html
{% extends 'core/base.html' %}

{% block title %}Add Client{% endblock %}

{% block content %}
    <div class = "py-6 px-6">
        <h1 class ="text-xl">Add Client</h1>

        {% if team.plan.max_clients > team.clients.all|length %}
            <form method ="post" action =".">
                {% csrf_token %}

                {{ form.as_p }}

                <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
            </form>
        {% else %}
            <div class="mt-4 px-6 py4 bg-red-300 rounded-xl text-white">
                Team has reached maximum number of clients
            </div> 
        {% endif %}
    </div>
{% endblock %}

greenCRM/client/templates/client/clients_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ client.name }}{% endblock %}

{% block content %}
    <div class = "py-6 px-6">
        <h1 class ="mb-4 text-xl">{{ client.org_name }}</h1>


        <p class ="font-semibold">Contact:</p>
        <p class="mb-2">{{ client.name }}</p>
        <p class="mb-2">{{ client.email }}</p>

        {% if client.description %}
            <p class="font-semibold">Description:</p>
            <p class="mb-2">{{ client.description }}</p>
        {% endif %}

        <p class="font-semibold">Created at:</p>
        <p class="mb-2">{{ client.created_at }}</p>

        <p class="font-semibold">Modified at:</p>
        <p class="mb-6">{{ client.modified_at }}</p>

        <hr class="my-4">

        <a href="{% url 'clients:edit' client.id %}" class="py-2 px-4 rounded-xl bg-emerald-400 text-white">Edit</a>
        <a href="{% url 'clients:delete' client.id %}" class="py-2 px-4 rounded-xl bg-red-400 text-white">Delete</a>

        <hr class="my-4">

        <h2 class="mb-4 text-2xl">Comments:</h2>

        <div class="space-y-4">
            {% for comment in client.comments.all %}
                <div class="bg-gray-100 p-6 rounded-xl">
                    <p class="mb-2"><strong>{{ comment.created_by }}</strong> @ {{ comment.created_at }}</p>

                    {{ comment.content }}
                </div>
            {% endfor %}
            <hr class="my-4 flex items-center justify-between">
        </div>

        <form method="post" action="{% url 'clients:add_comment' client.id %}">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="py-2 px-4 rounded-xl bg-emerald-400 text-white">Submit</button>
        </form>

        <hr class="my-4">

        <h2 class="mb-4 text-xl">Files</h2>

        <div class="space-y-4">
            {% for file in client.files.all %}
                <div class="bg-gray-100 p-6 rounded-xl">
                    <p class="mb-2"><strong>{{ file.created_by }}</strong> @ {{ file.created_at }}</p>

                   <a href="{{ file.file.url }}" class="py-2 px-4 rounded-xl bg-emerald-300 text-white">Download</a>
                </div>
            {% endfor %}

        </div>

        <hr class="my-4 flex items-center justify-between">

        <form method="post" action="{% url 'clients:add_file' client.id %}" enctype="multipart/form-data">
            {% csrf_token %}

            {{ fileform.as_p }}

            

            <button class="mt-4 py-2 px-4 rounded-xl bg-emerald-400 text-white">Submit</button>
        </form>

        <hr class="my-4 flex items-center justify-between">

        <a href="{% url 'clients:list' %}"class="py-2 px-4 rounded-xl bg-emerald-300 text-white">Back to Clients</a>  
        <a href="{% url 'dashboard:index' %}"class="py-2 px-4 rounded-xl bg-emerald-300 text-white">Back to Dashboard</a>
    </div>
{% endblock %}

greenCRM/client/templates/client/clients_edit.html
{% extends 'core/base.html' %}

{% block title %}Edit Client{% endblock %}

{% block content %}
    <div class = "py-6 px-6">
        <h1 class ="text-xl">Edit Client</h1>

        <form method ="post" action =".">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="py-4 px-8 bg-emerald-400 text-white rounded-xl">Submit</button>
        </form>
    </div>

{% endblock %}

greenCRM/client/templates/client/clients_list.html
{% extends 'core/base.html' %}

{% block title %}Clients{% endblock %}

{% block content %}
    <div class = "py-6 px-6">
        <h1 class ="mb-4 text-xl">Clients</h1>

        <a href="{% url 'clients:add' %}" class="inline-block py-4 px-6 bg-teal-600 rounded-xl text-white">Add client</a>
        <a href="{% url 'clients:export' %}" class="inline-block py-4 px-6 rounded-xl bg-green-400 text-white">Export clients list</a>
        <a href="{% url 'clients:report' %}" class="inline-block mb-4 py-4 px-6 bg-red-400 rounded-xl text-white">Generate Report</a>

        <dl class="mx-auto grid grid-cols-1 gap-px bg-gray-900/5 sm:grid-cols-2 lg:grid-cols-4">
            <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
              <dt class="text-sm font-medium leading-6 text-gray-500">Total Clients</dt>
              <dd class="text-xs font-medium text-gray-700">{{ active_team.clients.all|length }}</dd>
              <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900">{{ active_team.clients.all|length }}</dd>
            </div>
          
            <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
              <dt class="text-sm font-medium leading-6 text-gray-500">Total Monthly Orders</dt>
              <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900">{{ total_monthly_order }}</dd>
            </div>
          
            <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
              <dt class="text-sm font-medium leading-6 text-gray-500">Total Revenue</dt>
              <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900">${{ total_order_value }}</dd>
            </div>
 

            <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
              <dt class="text-sm font-medium leading-6 text-gray-500">Expenses</dt>
              <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900"></dd>
            </div>
          </dl>
          {% if clients %}
          <div class="mt-6 flex justify-between">
              <div class="w-1/2">
                  <p class="py-4 px-2 bg-orange-200 font-semibold w-full">Name</p>
                  {% for client in clients %}
                      <div class="flex justify-between">  
                          <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                              <a href="{% url 'clients:detail' client.id %}">{{ client.name }}</a>
                          </p>
                      </div>
                  {% endfor %}
              </div>
              <div class="w-1/2">
                  <p class="py-4 px-2 bg-orange-200 font-semibold w-full">Organization</p>
                  {% for client in clients %}
                      <div class="flex justify-between">  
                          <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ client.org_name }}</p>
                      </div>
                  {% endfor %}
              </div>
          </div>
   
    {% else %}
        <p class="px-2">No clients in databse</p>
    {% endif %}
    </div>
{% endblock %}    

greenCRM/client/templates/client/clients_report.html
{% extends 'core/base.html' %}

{% block title %}Clients Report{% endblock %}

{% block content %}
<div class="row mt-4 pt-4">
    <div class="col-md-4">
        <div class="border p-3">
            <h4 class ="mb-4 text-xl">Total Order Value by Client:</h4>
            <hr>
            <form method="POST">


            </form>
        </div>
    </div>

    <div class="col-md-8">
        <canvas id="myChart" width="400" height="200"></canvas>
        <script>
            var colors = ['#F44336', '#9C27B0', '#3F51B5', '#03A9F4', '#009688', '#8BC34A', '#FFC107'];
            var ctx = document.getElementById('myChart').getContext('2d');
            var myChart = new Chart(ctx, {
              type: 'bar',
              data: {
                labels: [{% for data in data %}'{{ data.org_name }}', {% endfor %}],
                datasets: [{
                  label: 'Total Order Value',
                  data: [{% for data in data %} {{ data.total_order_value}}, {% endfor %}],
                  backgroundColor: colors.slice(0, {{ data|length }}),
                  borderWidth: 1
                }]
              },
              options: {
                scales: {
                  y: {
                    beginAtZero: true
                  }
                }
              }
            });
          </script>
          
    </div>
<div class="py-6 px-6">
    <div class="col-md-4">
        <div class="border p-3">
            <h4 class ="mb-4 text-xl">Total Order Value by Client Type:</h4>
            <hr>
            <form method="POST">


            </form>
        </div>
    </div>

    <div class="col-md-8">
        <canvas id="myChart2" width="400" height="200"></canvas>
        <script>
            var store_values = [];
            var restaurant_values = [];

            {% for data in data %}
                {% if data.customer_type == 'store' %}
                    store_values.push({{ data.total_order_value }});
                {% else %}
                    restaurant_values.push({{ data.total_order_value }});
                {% endif %}
            {% endfor %}


            var ctx = document.getElementById('myChart2').getContext('2d');
            var myChart = new Chart(ctx, {
              type: 'bar',
              data: {
                labels: ['Store', 'Restaurant'],
                datasets: [{
                  label: 'Total Order Value',
                  data: [store_values.reduce((a, b) => a + b, 0), restaurant_values.reduce((a, b) => a + b, 0)],
                  backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)' 
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)'
                ],
                borderWidth: 1
                }]
              },
              options: {
                scales: {
                  y: {
                    beginAtZero: true
                  }
                }
              }
            });
          </script>
          
    </div>
</div>
{% endblock %}