greenCRM/dashboard/urls.py
from django.urls import path

from . import views 

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='index'), # can be left empty because dashbord url is located in greenCRM url file
]

greenCRM/greenCRM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about
from userprofile.forms import LoginForm


urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include ('lead.urls')), # configuring all urls beginning with dashboard/leads
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/', include('dashboard.urls')), # setting all urls that begin with dashbord to use dashboard.urls file
    path('dashboard/teams/', include('team.urls')),
    path('dashboard/report/', include ('report.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

greenCRM/lead/urls.py
from django.urls import path

from . import views 

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name ='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name= 'detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='converted'),
    path('<int:pk>/add-comment', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name='add_file'),
    path('add/', views.LeadCreateView.as_view(), name='add'),
    path('export/', views.leads_export, name='export'),
]

greenCRM/lead/models.py
from django.contrib.auth.models import User
from django.db import models

from team.models import Team

class Lead(models.Model):
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    # tuple 
    CHOICES_PRIORITY = (
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High'),
    )

    NEW = 'new'
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'

    CHOICES_STATUS = (
        (NEW, 'New'),
        (CONTACTED, 'Contacted'),
        (WON, 'Won'),
        (LOST, 'Lost'),
    )

    team = models.ForeignKey(Team, related_name='leads', on_delete=models.CASCADE)
    name = models.CharField(max_length=225)
    org_name = models.CharField(max_length=225, default='unknown')
    phone_number = models.CharField(max_length=20, default='unknown')
    email = models.EmailField()
    address = models.CharField(max_length=255, default='unknown')
    description = models.TextField(blank=True, null=True)
    priority = models.CharField(max_length = 10, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='leads', on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

class LeadFile(models.Model):
    team = models.ForeignKey(Team, related_name='lead_files', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='leadfiles')
    created_by = models.ForeignKey(User, related_name='lead_files', on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

class Comment(models.Model):
    team = models.ForeignKey(Team, related_name='lead_comments', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='lead_comments', on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

greenCRM/lead/forms.py
from django import forms 

from . models import Lead, Comment, LeadFile

INPUT_CLASS = 'w-full py-4 px-6 rounded-xl bg-gray-100'

class AddLeadForm(forms.ModelForm):  #using modelForm so django will create this for us based on information in the clas meta
    name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Lead Name',
        'class': INPUT_CLASS}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder':'Email',
        'class': INPUT_CLASS}))
    description = forms.CharField(widget=forms.Textarea(attrs={
        'class': INPUT_CLASS}))

    class Meta:
        model = Lead
        fields = ('name','email','org_name','phone_number','address', 'description', 'priority', 'status',)  #whihc fields I want to show in the form

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

class AddFileForm(forms.ModelForm):
    class Meta:
        model = LeadFile
        fields = ('file',)

greenCRM/lead/views.py
import csv

from django.contrib import messages 
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView, View

from .forms import AddCommentForm, AddFileForm
from .models import Lead

from client.models import Client, Comment as ClientComment
from team.models import Team

@login_required
def leads_export(request):
    leads = Lead.objects.filter(created_by=request.user)

    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attatchment; filename="leads.csv"'}
    )

    writer = csv.writer(response)
    writer.writerow(['Org Name','Contact', 'email','Phone Number','Address', 'priority', 'status', 'Created at', 'Created by'])
    
    for lead in leads:   #looping through all the clients and adding them to the file:
        writer.writerow([lead.org_name, lead.name, lead.email, lead.phone_number, lead.address, lead.priority, lead.status, lead.created_at, lead.created_by])

    return response

class LeadListView(LoginRequiredMixin, ListView):
    model = Lead

    def get_queryset(self):
        queryset = super(LeadListView, self).get_queryset()
        queryset = queryset.filter(created_by=self.request.user, converted_to_client=False)

        return queryset
#getting the number of new leads and high priority leads for active team
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        active_team = self.request.user.userprofile.active_team
        context['uncontacted_leads_count'] = Lead.objects.filter(team=active_team, status='new').count()
        context['high_priority_leads_count'] = Lead.objects.filter(team=active_team, priority='high').count()
        
        return context

class LeadDetailView(LoginRequiredMixin, DetailView):
    model = Lead

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AddCommentForm()
        context['fileform'] = AddFileForm()

        return context

    def get_queryset(self):
        queryset = super(LeadDetailView, self).get_queryset()
        queryset = queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))
        return queryset

class LeadDeleteView(LoginRequiredMixin, DeleteView):
    model = Lead
    success_url = reverse_lazy('leads:list')

    def get_queryset(self):
        queryset = super(LeadDeleteView, self).get_queryset()
        queryset = queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))

        return queryset

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

class LeadUpdateView(LoginRequiredMixin, UpdateView):
    model = Lead
    fields = ('name','org_name','phone_number', 'email', 'address', 'description', 'priority', 'status',)
    success_url = reverse_lazy('leads:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edit lead'

        return context

    def get_queryset(self):
        queryset = super(LeadUpdateView, self).get_queryset()
        queryset = queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))

        return queryset

   

class LeadCreateView(LoginRequiredMixin, CreateView):
    model = Lead
    fields = ('name','org_name','phone_number','email','address', 'description', 'priority', 'status',)
    success_url = reverse_lazy('leads:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        team = self.request.user.userprofile.active_team
        context['team'] = team
        context['title'] = 'Add lead'

        return context


    def form_valid(self, form):

        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.team = self.request.user.userprofile.active_team
        self.object.save()

        return redirect(self.get_success_url())

class AddFileView(View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')

        form = AddFileForm(request.POST, request.FILES)

        if form.is_valid():
    
            file = form.save(commit=False)
            file.team = self.request.user.userprofile.active_team
            file.lead_id = pk
            file.created_by = request.user
            file.save()

            return redirect('leads:detail', pk=pk)


class AddCommentView(View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')

        form = AddCommentForm(request.POST)

        if form.is_valid():
       
            comment = form.save(commit=False)
            comment.team = self.request.user.userprofile.active_team
            comment.created_by = request.user
            comment.lead_id = pk 
            comment.save()

        return redirect('leads:detail', pk=pk)

class ConvertToClientView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')

        lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
        team = self.request.user.userprofile.active_team

        client = Client.objects.create(
            name=lead.name,
            email=lead.email,
            description=lead.description,
            created_by=request.user,
            team = team,
        )

        lead.converted_to_client = True
        lead.save()

        team.converted_leads += 1
        team.save()

        #converting lead commments to client comments

        comments = lead.comments.all()

        for comment in comments:
            ClientComment.objects.create(
                client = client,
                content = comment.content,
                created_by = comment.created_by,
                team = team

            )

        #show message and redirect

        messages.success(request, 'Lead has been converted to client.')

        return redirect('leads:list')

greenCRM/lead/templates/lead/lead_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ lead.name }}{% endblock %}

{% block content %}
<div class = "py-6 px-6">
    <h1 class ="mb-4 text-xl">{{ lead.org_name }}</h1>

    <p class ="font-semibold">Contact:</p>
    <p class="mb-2">{{ lead.name }}</p>
    <p class="mb-2">{{ lead.email }}</p>
    <p class="mb-2">{{ lead.phone_number }}</p>

    {% if client.description %}
        <p class="font-semibold">Description:</p>
        <p class="mb-2">{{ lead.description }}</p>
    {% endif %}

    <p class="font-semibold">Created at:</p>
    <p class="mb-2">{{ lead.created_at }}</p>

    <p class="font-semibold">Modified at:</p>
    <p class="mb-6">{{ lead.modified_at }}</p>

    <hr class="my-4">

        <form id="lead_delete_form" method="post" action="{% url 'leads:delete' lead.id %}">
            {% csrf_token %}
        </form>

        <a href="{% url 'leads:converted' lead.id %}" class="py-2 px-4 rounded-xl bg-emerald-400 text-white">Convert to client</a>
        <a href="{% url 'leads:edit' lead.id %}" class="py-2 px-4 rounded-xl bg-blue-300 text-white">Edit</a>
        <a href="#" onclick="document.getElementById('lead_delete_form').submit();" class="py-2 px-4 rounded-xl bg-red-400 text-white">Delete</a>

        <hr class="my-4">

        <h2 class="mb-4 text-xl">Comments</h2>

        <div class="space-y-4">
            {% for comment in lead.comments.all %}
                <div class="bg-gray-100 p-6 rounded-xl">
                    <p class="mb-2"><strong>{{ comment.created_by }}</strong> @ {{ comment.created_at }}</p>

                    {{ comment.content }}
                </div>
            {% endfor %}

        </div>

        <form method="post" action="{% url 'leads:add_comment' lead.id %}">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="py-2 px-4 rounded-xl bg-blue-300 text-white">Submit</button>
        </form>

        <hr class="my-4">

        <h2 class="mb-4 text-xl">Files</h2>

        <div class="space-y-4">
            {% for file in lead.files.all %}
                <div class="bg-gray-100 p-6 rounded-xl">
                    <p class="mb-2"><strong>{{ file.created_by }}</strong> @ {{ file.created_at }}</p>

                   <a href="{{ file.file.url }}">Download</a>
                </div>
            {% endfor %}

        </div>

        <form method="post" action="{% url 'leads:add_file' lead.id %}" enctype="multipart/form-data">
            {% csrf_token %}

            {{ fileform.as_p }}

            <button class="py-2 px-4 rounded-xl bg-emerald-400 text-white">Submit</button>
        </form>

        <hr class="my-4">

        <a href="{% url 'leads:list' %}"class="py-2 px-4 rounded-xl bg-emerald-400 text-white">Back to leads</a>  
        <a href="{% url 'dashboard:index' %}"class="py-2 px-4 rounded-xl bg-emerald-400 text-white">Back to Dashboard</a>
    </div>
{% endblock %}

greenCRM/lead/templates/lead/lead_form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class = "py-6 px-6">
        <h1 class ="text-xl">{{ title }}</h1>

        {% if team.plan.max_leads > team.leads.count or title == 'Edit Lead' %}
            <form method ="post" action =".">
                {% csrf_token %}

                {{ form.as_p }}

                <hr class="my-4">

                <button class="py-4 px-8 bg-emerald-400 text-white rounded-xl">Submit</button>
                <div style="padding-top: 4rem;">
                    <a href="{% url 'leads:list' %}"class="py-2 px-4 rounded-xl bg-emerald-400 text-white">Back to leads</a>  
                    <a href="{% url 'dashboard:index' %}"class="py-2 px-4 rounded-xl bg-emerald-400 text-white">Back to Dashboard</a>
                </div>
            </form>
        {% else %}
            <div class="mt-4 px-6 py4 bg-red-300 rounded-xl text-white">
                Team has reached maximum number of leads
            </div> 
        {% endif %}
    </div>

{% endblock %}

greenCRM/lead/templates/lead/lead_list.html
{% extends 'core/base.html' %}

{% block title %}Leads{% endblock %}

{% block content %}
    <div class = "py-6 px-6">
        <h1 class ="mb-4 text-xl">Leads</h1>

        <a href="{% url 'leads:add' %}" class="inline-block py-4 px-6 bg-teal-600 rounded-xl text-white">Add Lead</a>
        <a href="{% url 'leads:export' %}" class="inline-block py-4 px-6 rounded-xl bg-green-400 text-white">Export leads</a>

        <dl class="mx-auto grid grid-cols-1 gap-px bg-gray-900/5 sm:grid-cols-2 lg:grid-cols-4">
            <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
              <dt class="text-sm font-medium leading-6 text-gray-500">Total Leads</dt>
              <dd class="text-xs font-medium text-gray-700">{{ active_team.leads.all|length }}</dd>
              <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900">{{ active_team.leads.all|length }}</dd>
            </div>
          
            <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
              <dt class="text-sm font-medium leading-6 text-gray-500">Converted Leads</dt>
              <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900">{{ active_team.converted_leads }}</dd>
            </div>
          
            <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
              <dt class="text-sm font-medium leading-6 text-gray-500">New Leads</dt>
              <dd class="text-xs font-medium text-gray-700">(pending contact)</dd>
              <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900">{{ uncontacted_leads_count }}</dd>
            </div>
          
            <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
              <dt class="text-sm font-medium leading-6 text-gray-500">High Priority Leads</dt>
              <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900">{{ high_priority_leads_count }}</dd>
            </div>
          </dl>
          

    {% if object_list %}
        <div class="mt-6 flex justify-between">
            <p class="py-4 px-2 bg-orange-200 font-semibold w-full">Name</p>
            <p class="py-4 px-2 bg-orange-200 font-semibold w-full">Priority</p>
            <p class="py-4 px-2 bg-orange-200 font-semibold w-full">Status</p>
        </div>

        {% for lead in object_list %}
            <div class="flex justify-between">  
                <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                    <a href="{%url 'leads:detail' lead.id %}">{{ lead.name }}</a>
                </p>
                <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ lead.get_priority_display }}</p>
                <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ lead.get_status_display }}</p>
            </div>
        {% endfor %}
    {% else %}
        <p class="px-2">No leads in databse</p>
    {% endif %}
    </div>
{% endblock %}    